---
deployment:
  tasks:
    - /bin/rsync -rv --no-perms --no-owner --no-group --exclude='.git' --exclude='backups' --exclude='uploads' --exclude='.cpanel.yml' --exclude='_dev/' --exclude='database/' --exclude='README.md' --exclude='package.json' --exclude='config/database.php' ./ /home/mpeljgto/public_html/