<?php
declare(strict_types=1);

require __DIR__ . '/db.php';

$user = require_role($pdo, ['OWNER']);

require_once __DIR__ . '/../services/PermissionService.php';
PermissionService::requirePermission($user['role'], 'reports.generate');

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    respond(['success' => false, 'message' => 'Method not allowed.'], 405);
}

$format = strtolower((string)($_GET['format'] ?? 'json'));
if (!in_array($format, ['json', 'csv'], true)) {
    respond(['success' => false, 'message' => 'Invalid format. Allowed: json, csv.'], 422);
}

$startDate = trim((string)($_GET['start_date'] ?? ''));
$endDate = trim((string)($_GET['end_date'] ?? ''));
if ($startDate !== '' && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $startDate)) {
    respond(['success' => false, 'message' => 'Invalid start_date format. Use YYYY-MM-DD.'], 422);
}
if ($endDate !== '' && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $endDate)) {
    respond(['success' => false, 'message' => 'Invalid end_date format. Use YYYY-MM-DD.'], 422);
}
if ($startDate !== '' && $endDate !== '' && $startDate > $endDate) {
    respond(['success' => false, 'message' => 'start_date must not be after end_date.'], 422);
}

require_once __DIR__ . '/../services/ReportService.php';
$reportService = new ReportService();

$report = $reportService->generateFullReport(
    $startDate !== '' ? $startDate : null,
    $endDate !== '' ? $endDate : null,
    $user['name']
);

log_activity((int)$user['id'], 'report_generated', "Format: {$format}, Period: {$startDate} to {$endDate}");

if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="shop-report-' . date('Y-m-d') . '.csv"');

    $sanitizeCsv = function (string $val): string {
        if (in_array($val[0] ?? '', ['=', '+', '-', '@', "\t", "\r"], true)) {
            $val = "'" . $val;
        }
        return $val;
    };

    $out = fopen('php://output', 'w');
    fputcsv($out, [$sanitizeCsv('Clothing Shop Report'), $report['generated_at']]);
    fputcsv($out, ['Generated by', $report['generated_by']]);
    fputcsv($out, []);
    fputcsv($out, ['Period', $report['period_start'] ?: 'All time', $report['period_end'] ?: '']);
    fputcsv($out, ['Summary']);
    fputcsv($out, ['Total products', $report['summary']['total_products']]);
    fputcsv($out, ['Total sales', $report['summary']['total_sales']]);
    fputcsv($out, ['Period revenue (TSH)', $report['summary']['period_revenue']]);
    fputcsv($out, ['Period profit (TSH)', $report['summary']['period_profit']]);
    fputcsv($out, ['Period expenses (TSH)', $report['summary']['period_expenses']]);
    fputcsv($out, ['Period net profit (TSH)', $report['summary']['period_net_profit']]);
    fputcsv($out, []);
    fputcsv($out, ['Products']);
    fputcsv($out, ['Name', 'Stock', 'Buying', 'Selling', 'Profit/unit', 'Status']);
    foreach ($report['products'] as $product) {
        fputcsv($out, [
            $sanitizeCsv($product['product_name']),
            $product['total_stock'],
            $product['buying_price'],
            $product['selling_price'],
            $product['profit_per_unit'],
            $product['stock_status'],
        ]);
    }
    fputcsv($out, []);
    fputcsv($out, ['Sales']);
    fputcsv($out, ['Receipt', 'Amount', 'Profit', 'Date', 'Seller']);
    foreach ($report['recent_sales'] as $sale) {
        fputcsv($out, [
            $sale['receipt_number'],
            $sale['total_amount'],
            $sale['total_profit'],
            $sale['sale_date'],
            $sanitizeCsv($sale['seller_name']),
        ]);
    }
    fclose($out);
    exit;
}

respond(['success' => true, 'report' => $report]);
