<?php
declare(strict_types=1);

require __DIR__ . '/db.php';

$user = require_role($pdo, ['OWNER']);

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    respond(['success' => false, 'message' => 'Method not allowed.'], 405);
}

$format = strtolower((string)($_GET['format'] ?? 'json'));

$startDate = trim((string)($_GET['start_date'] ?? ''));
$endDate = trim((string)($_GET['end_date'] ?? ''));

require_once __DIR__ . '/../services/ReportService.php';
$reportService = new ReportService();

$report = $reportService->generateFullReport(
    $startDate !== '' ? $startDate : null,
    $endDate !== '' ? $endDate : null,
    $user['name']
);

if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="shop-report-' . date('Y-m-d') . '.csv"');

    $out = fopen('php://output', 'w');
    fputcsv($out, ['Clothing Shop Report', $report['generated_at']]);
    fputcsv($out, ['Generated by', $report['generated_by']]);
    fputcsv($out, []);
    fputcsv($out, ['Period', $report['period_start'] ?: 'All time', $report['period_end'] ?: '']);
    fputcsv($out, ['Summary']);
    fputcsv($out, ['Total products', $report['summary']['total_products']]);
    fputcsv($out, ['Total sales', $report['summary']['total_sales']]);
    fputcsv($out, ['Period revenue (TSH)', $report['summary']['period_revenue']]);
    fputcsv($out, ['Period profit (TSH)', $report['summary']['period_profit']]);
    fputcsv($out, ['Period expenses (TSH)', $report['summary']['period_expenses']]);
    fputcsv($out, ['Period net profit (TSH)', $report['summary']['period_net_profit']]);
    fputcsv($out, []);
    fputcsv($out, ['Products']);
    fputcsv($out, ['Name', 'Stock', 'Buying', 'Selling', 'Profit/unit', 'Status']);
    foreach ($report['products'] as $product) {
        fputcsv($out, [
            $product['product_name'],
            $product['total_stock'],
            $product['buying_price'],
            $product['selling_price'],
            $product['profit_per_unit'],
            $product['stock_status'],
        ]);
    }
    fputcsv($out, []);
    fputcsv($out, ['Sales']);
    fputcsv($out, ['Receipt', 'Amount', 'Profit', 'Date', 'Seller']);
    foreach ($report['recent_sales'] as $sale) {
        fputcsv($out, [
            $sale['receipt_number'],
            $sale['total_amount'],
            $sale['total_profit'],
            $sale['sale_date'],
            $sale['seller_name'],
        ]);
    }
    fclose($out);
    exit;
}

respond(['success' => true, 'report' => $report]);
