<?php
declare(strict_types=1);

require __DIR__ . '/db.php';

$user = require_role($pdo, ['OWNER']);

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    respond(['success' => false, 'message' => 'Method not allowed.'], 405);
}

$format = strtolower((string)($_GET['format'] ?? 'json'));
$threshold = low_stock_threshold($pdo);

$startDate = trim((string)($_GET['start_date'] ?? ''));
$endDate = trim((string)($_GET['end_date'] ?? ''));

$dateFilter = '';
$dateParams = [];
if ($startDate !== '' && $endDate !== '') {
    $dateFilter = ' AND sale_date >= :start_date AND sale_date <= :end_date';
    $dateParams = ['start_date' => $startDate . ' 00:00:00', 'end_date' => $endDate . ' 23:59:59'];
}

$totalProducts = (int)$pdo->query('SELECT COUNT(*) FROM products WHERE status = "active"')->fetchColumn();

$salesStmt = $pdo->prepare(
    "SELECT COUNT(*) AS count, COALESCE(SUM(total_amount), 0) AS revenue, COALESCE(SUM(total_profit), 0) AS profit
     FROM sales WHERE payment_status = 'paid'{$dateFilter}"
);
$salesStmt->execute($dateParams);
$salesRow = $salesStmt->fetch();
$totalSales = (int)$salesRow['count'];
$periodRevenue = (float)$salesRow['revenue'];
$periodProfit = (float)$salesRow['profit'];

$products = $pdo->query(
    'SELECT product_name, total_stock, buying_price, selling_price, profit_per_unit, stock_status
     FROM product_stock_summary
     ORDER BY product_name'
)->fetchAll();

$recentSales = [];
if ($startDate !== '' && $endDate !== '') {
    $recentStmt = $pdo->prepare(
        "SELECT s.receipt_number, s.total_amount, s.total_profit, s.sale_date, u.name AS seller_name
         FROM sales s
         JOIN users u ON u.id = s.sold_by
         WHERE s.payment_status = 'paid'{$dateFilter}
         ORDER BY s.sale_date DESC
         LIMIT 100"
    );
    $recentStmt->execute($dateParams);
    $recentSales = $recentStmt->fetchAll();
}

$report = [
    'generated_at' => date('Y-m-d H:i:s'),
    'generated_by' => $user['name'],
    'currency' => 'TSH',
    'period_start' => $startDate,
    'period_end' => $endDate,
    'low_stock_threshold' => $threshold,
    'summary' => [
        'total_products' => $totalProducts,
        'total_sales' => $totalSales,
        'period_revenue' => $periodRevenue,
        'period_profit' => $periodProfit,
    ],
    'products' => $products,
    'recent_sales' => $recentSales,
];

if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="shop-report-' . date('Y-m-d') . '.csv"');

    $out = fopen('php://output', 'w');
    fputcsv($out, ['Clothing Shop Report', $report['generated_at']]);
    fputcsv($out, ['Generated by', $report['generated_by']]);
    fputcsv($out, []);
    fputcsv($out, ['Period', $startDate ?: 'All time', $endDate ?: '']);
    fputcsv($out, ['Summary']);
    fputcsv($out, ['Total products', $totalProducts]);
    fputcsv($out, ['Total sales', $totalSales]);
    fputcsv($out, ['Period revenue (TSH)', $periodRevenue]);
    fputcsv($out, ['Period profit (TSH)', $periodProfit]);
    fputcsv($out, []);
    fputcsv($out, ['Products']);
    fputcsv($out, ['Name', 'Stock', 'Buying', 'Selling', 'Profit/unit', 'Status']);
    foreach ($products as $product) {
        fputcsv($out, [
            $product['product_name'],
            $product['total_stock'],
            $product['buying_price'],
            $product['selling_price'],
            $product['profit_per_unit'],
            $product['stock_status'],
        ]);
    }
    fputcsv($out, []);
    fputcsv($out, ['Sales']);
    fputcsv($out, ['Receipt', 'Amount', 'Profit', 'Date', 'Seller']);
    foreach ($recentSales as $sale) {
        fputcsv($out, [
            $sale['receipt_number'],
            $sale['total_amount'],
            $sale['total_profit'],
            $sale['sale_date'],
            $sale['seller_name'],
        ]);
    }
    fclose($out);
    exit;
}

respond(['success' => true, 'report' => $report]);
